### ISSUE TITLE
The download url can't open

### ISSUE THREAD

**Issue by seriouslym** [sfu-discourse-lab/SOCC#2]

**Comment by maitetaboada** [comment]
Thanks for pointing this out! The original repository has been discontinued, but I have moved the file to Kaggle. The link is updated here on GitHub and here is the direct download link: [https://www.kaggle.com/mtaboada/sfu-opinion-and-comments-corpus-socc](https://www.kaggle.com/mtaboada/sfu-opinion-and-comments-corpus-socc)

**Comment by seriouslym** [comment]
Thanks a lot!
